Dev
MMOsei/Sparta-Custom-Bootstrap pull request #3
Opened 2018-05-24 07:48 UTC by MMOsei

I would like to merge the Dev branch to master. Thank you.

2018-05-24 16:55 UTC, ACKAdeyemi commented on index.html
> +    <div class="overlay jumbotron landing-jt">
Indent this <div> tag and everything below it down to line 90

2018-05-24 16:59 UTC, ACKAdeyemi commented on index.html
> +        <p></p>
Remove this <p> tag.

2018-05-24 17:13 UTC, ACKAdeyemi requested changes
Website looks cool and has many great features, everything works (mostly), good comments but unfortunately the code isn't formatted well.

Go through all pages and indent correctly and consistently. Also delete unnecessary spaces between lines and be consistent. So either 1 space or no spaces between divs, css selectors, etc.

Remove unnecessary commented lines of code e.g. lines where you were experimenting, lines that don't work, etc.

Remove empty tags. 

index issues:
- Remove p tag on line 50
- Logo doesn't link to home (logo doesn't link to home on any of the pages)

Get that sorted and should be fine.

Could add a couple more explanatory comments in your css doc.

2018-05-25 07:13 UTC, MMOsei commented
Hi @ACKAdeyemi @isabelvalente ,

All changes made, as requested, and ready for dev to be merged to master.

Ready for review.

Many thanks,

Mimi

2018-05-25 08:16 UTC, ACKAdeyemi approved these changes

2018-05-25 08:20 UTC, merged